spring:
  application:
    name: sample
  redis:
    url: redis://:@127.0.0.1:6380 # 和 host，port, username, password配置效果一样
    host: localhost
    username: ''
    password: ''
    port: 6380
  datasource:
    driverClassName: org.h2.Driver # 根据所需数据库修改
    url: jdbc:h2:file:/tmp/sample # 根据所需数据库修改
    username: root
    password: 123456
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
      mode: always
  h2:
    console:
      path: /h2-console
      enabled: true
server:
  port: 8080
infra:
  trace:
    enabled: false # 是否开启trace
    zipkin:
      url: "http://localhost:9411/api/v2/spans"
      sampler: "1.0F"
grpc:
  pure:
    app-name: greeter
    server:
      port: 9999
    discovery:
      type: direct # direct 直连，nacos 使用nacos作为注册中心
      nacos:
        address: 127.0.0.1:8848
        username: nacos
        password: nacos
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /management
  endpoint:
    health:
      show-details: "always"
      enabled: false
  server:
    port: 7777