spring:
  application:
    name: application
  redis:
    url: redis://:@127.0.0.1:6379
    host: localhost
    username: ''
    password: ''
    port: 6379
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/sample
    username: root
    password: 123456
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
      mode: always
  h2:
    console:
      path: /h2-console
      enabled: true
server:
  port: 8080
infra:
  trace:
    enable: true
    zipkin:
      url: "http://localhost:9411/api/v2/spans"
      sampler: "1.0F"
  config:
    enable: true
    git:
      uri: git@github.com:xincao9/infra-framework.git
      dir: /tmp
      remote: origin
      remote-branch-name: main
grpc:
  pure:
    app-name: greeter
    server:
      port: 9999
    discovery:
      type: nacos
      nacos:
        address: 127.0.0.1:8848
        username: nacos
        password: nacos
