infra:
  config:
    app-name: sample
    enabled: true
    type: git
    git:
      uri: https://github.com/xincao9/sample-config-repo.git
      remote: origin
      remote-branch-name: main
      delay-seconds: 30