infra:
  config:
    app-name: sample
    enabled: true
    type: git
    git:
      uri: git@github.com:xincao9/sample-config-repo.git
      dir: /Users/caoxin/.config
      remote: origin
      remote-branch-name: main