# 基础设施配置
grpc:
  pure:
    app-name: ${spring.application.name}
    server:
      port: 9999
    discovery:
      type: nacos # direct 直连，nacos 使用nacos作为注册中心
      nacos:
        address: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: grpc
infra:
  trace:
    enabled: false # 是否开启trace
    zipkin:
      url: "http://localhost:9411/api/v2/spans"
      sampler: "1.0F"
  registry:
    enabled: true # 是否开启服务注册
    type: nacos
    nacos:
      address: 127.0.0.1:8848
      username: nacos
      password: nacos
      namespace: api
    app-name: ${spring.application.name}
    port: ${server.port}
spring:
  quartz:
    job-store-type: jdbc # 可选 memory
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.scheduler.instanceName: ${spring.application.name}
      org.quartz.threadPool.threadCount: 5
      # 数据库相关配置
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.dataSource: myDS
      org.quartz.dataSource.myDS.provider: hikaricp
      org.quartz.dataSource.myDS.driver: com.mysql.cj.jdbc.Driver #org.h2.Driver
      org.quartz.dataSource.myDS.URL: jdbc:mysql://localhost:3306/quartz #jdbc:h2:file:/tmp/quartz
      org.quartz.dataSource.myDS.user: root
      org.quartz.dataSource.myDS.password:
      # 集群相关配置
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.clusterCheckinInterval: 20000
      org.quartz.scheduler.instanceId: AUTO
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /management
  endpoint:
    health:
      show-details: "always"
      enabled: false
  server:
    port: 7777
springdoc:
  use-management-port: true