spring:
  profiles:
    active: infrastructure # infrastructure 环境必须选择；spring.profiles.active: infrastructure,prod
  application:
    name: sample
  redis:
    url: redis://:@127.0.0.1:6380 # 和 host，port, username, password配置效果一样
    host: localhost
    username: ''
    password: ''
    port: 6380
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver # org.h2.Driver
    url: jdbc:mysql://localhost:3306/sample # jdbc:h2:file:/tmp/sample
    username: root
    password:
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
      mode: always
  h2:
    console:
      path: /h2-console
      enabled: true
server:
  port: 8080